function [x,z] = get_line()
% Plots variables directly loaded from file
% h = pic.PLOTMAP({'Ey','Ez'})
x = [];
z = [];
xinterp = [];
zinterp = [];
ninp = 0;
disp('Hit enter when you are ready.')
while 1  
  keydown = wfbp;
  if keydown
    char = get(fig, 'CurrentCharacter');
  end
  if(char == 13) % & how_many ~= 0)
    % if the return key was pressed, char will == 13,
    % and that's our signal to break out of here whether
    % or not we have collected all the requested data
    % points.
    % If this was an early breakout, don't include
    % the <Return> key info in the return arrays.
    % We will no longer count it if it's the last input.
    break;
  end
                  
  [x_,z_] = ginput(1);
  x = [x x_]; 
  z = [z z_];   
  if ninp > 1
    xinterp = interp1(x,1:numel(x),1:0.1:1:numel(x),'spline');
    zinterp = interp1(z,1:numel(z),1:0.1:1:numel(z),'spline');
  end

  ninp = ninp + 1;
  hold(gca,'on')
  
    plot(gca,x,z,x_,z_,'o',xinterp,zinterp)
  
  
  hold(gca,'off')
  
  if(char == 13) % & how_many ~= 0)
    % if the return key was pressed, char will == 13,
    % and that's our signal to break out of here whether
    % or not we have collected all the requested data
    % points.
    % If this was an early breakout, don't include
    % the <Return> key info in the return arrays.
    % We will no longer count it if it's the last input.
    break;
  end
end      


end

function key = wfbp
%WFBP   Replacement for WAITFORBUTTONPRESS that has no side effects.

fig = gcf;
current_char = []; %#ok<NASGU>

% Now wait for that buttonpress, and check for error conditions
waserr = 0;
try
    h=findall(fig,'Type','uimenu','Accelerator','C');   % Disabling ^C for edit menu so the only ^C is for
    set(h,'Accelerator','');                            % interrupting the function.
    keydown = waitforbuttonpress;
    current_char = double(get(fig,'CurrentCharacter')); % Capturing the character.
    if~isempty(current_char) && (keydown == 1)          % If the character was generated by the
        if(current_char == 3)                           % current keypress AND is ^C, set 'waserr'to 1
            waserr = 1;                                 % so that it errors out.
        end
    end
    
    set(h,'Accelerator','C');                           % Set back the accelerator for edit menu.
catch %#ok<CTCH>
    waserr = 1;
end
drawnow;
if(waserr == 1)
    set(h,'Accelerator','C');                          % Set back the accelerator if it errored out.
    error(message('MATLAB:ginput:Interrupted'));
end

if nargout>0, key = keydown; end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end
